### ISSUE TITLE
Vue: focus is reset after 1 keypress

### ISSUE THREAD

**Issue by arwinvdv** [hodgef/simple-keyboard#1007]
**Simple-keyboard version**
Tested in 3.0.40 in latest Chrome and in sandbox: https://hodgef.com/simple-keyboard/editor/?d=hodgef/vue-simple-keyboard/tree/master

**Describe the bug**
When you type for example `test` and you set the cursor between the `e` and `s` and you type for example `x` letter you see `texst`. But if you type another `x` you see `texstx` instead of `texxst`.

**Screenshots**
![simple-keyboard-vue-focus-problem](https://user-images.githubusercontent.com/7255485/116576884-452bc780-a910-11eb-8182-013655711ec1.gif)

**Comment by hodgef** [comment]
Hello @arwinvdv,

I was not able to reproduce this in the [same vue sandbox](https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/).

Unfortunately, sometimes the sandbox is unreliable, so if you're still having this issue locally I'd appreciate if you could provide a test git repo with your implementation so I can take a look.

![test](https://user-images.githubusercontent.com/25509135/116604835-a649a000-a8fc-11eb-9cb5-faccd5501c65.gif)

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Actually you are correct, this is passing in Win10 - Chromium Edge 90,  Firefox 88 but failing on Chrome 90.

I'll take a closer look later today. Thanks!

**Comment by hodgef** [comment]
Hello @arwinvdv,

Sorry for the delay. It appears this issue was caused by a regression introduced while attempting to fix ticket https://github.com/hodgef/react-simple-keyboard/issues/1140. I have reverted that change and the caret positioning appears to be fixed now.

Could you upgrade to **simple-keyboard 3.0.54** (latest) and see if it's fixed in your end? I'm going to deprecate versions 3.0.46 to 3.0.53.

Regards,
Francisco Hodge

**Comment by arwinvdv** [comment]
@hodgef Thank you very much! What a fast fix, I will buy you a coffee!

**Comment by hodgef** [comment]
Wow thanks @arwinvdv! Much appreciated!
