### ISSUE TITLE
Focus is not correctly kept on the input since preventMouseDownDefault is not enough.

### ISSUE THREAD

**Issue by philfontaine** [hodgef/simple-keyboard#1029]
**Simple-keyboard version**
3.0.60

**Describe the bug**

In the docs, it is stated that `preventMouseDownDefault` "Prevents loss of input focus from clicking simple-keyboard buttons".

It "works" to keep the focus on the input, but it does not work properly. When the caret is in the middle of the word and we click on a key, the focus will stay on the input, but the caret will be moved to the end of the input (even though the key is inserted at the correct position).

https://codesandbox.io/s/hopeful-buck-rjzvr?file=/src/index.js

Steps:
1. Write ABC123 in the input
2. Place the caret between ABC and 123
3. Click on a key
4. The new key is inserted at the correct place in the input, but the input caret is now at the end.

To make this work properly, I think we might be missing two options (I'm not sure it's just a guess), 
- preventClickDefault
- stopClickPropagation

**Screenshots**

**Comment by hodgef** [comment]
Hello @philfontaine,

simple-keyboard does not manage user inputs. It only interacts with inputs in order to update its internal caret position, but that's pretty much it.

In my view, the issue that you're raising is about general Javascript behavior. In your `onChange` you are setting a value for your input. If you would like to also set the caret position, then you have to call [element.setSelectionRange](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange).

In the docs for [preventMouseDownDefault](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/) you can find examples that better illustrate this. Please feel free to check them out.

Regards,
Francisco Hodge
