### ISSUE TITLE
Max Length

### ISSUE THREAD

**Issue by zoolfadhlie** [hodgef/simple-keyboard#11]
Hi thanks for the great work you have done.. 

how to limit the number of character in the input. Normally we will use maxlength attribute. But in this case maxlength is does not working.. 

And also is it possible to move to next input box by clicking at tab or enter button?

cheers

zul

**Comment by hodgef** [comment]
Hello @zoolfadhlie,

Those are great requests. I think this `MaxLength` property should be built-in. I will release it in a few hours.

Regarding the moving to the next input box, you can absolutely do that, but on your own implementation. Simple-keyboard doesn't really handle the input elements, just the string. You can even chose not to use inputs at all. So for your use case I suggest something custom like this:

[![Edit simple-keyboard next input on enter demo - npm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ykz9xkwlqv?module=%2Fsrc%2Findex.js)

You may notice in that example that I set a custom keyboard layout, changing the button `{tab}` for `{tabBtn}`. This is because simple-keyboard enters a tab character (`\t`) whenever I hit the default tab button. On the next release, I will push an option to disable this functionality and will update the demo.

Thanks! Stay tuned for updates
