### ISSUE TITLE
Layouts not working

### ISSUE THREAD

**Issue by m-waqarhussain** [hodgef/simple-keyboard#1145]
This demo layout is not working.

This is the default demo layout located here, https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-layouts-demos/tree/cdn is not working. it just keeps saying transpiling modules.

![image](https://user-images.githubusercontent.com/87567017/126033912-a4e964c3-811b-42a0-a052-f7a717583a1c.png)
a

When i rant it locally it is showing this error

![image](https://user-images.githubusercontent.com/87567017/126034122-bc0bc5ff-3b9f-4576-953b-a6267c032704.png)

**Comment by hodgef** [comment]
I tried this locally and it works just fine

![image](https://user-images.githubusercontent.com/25509135/126075546-87cb951a-616b-4a9e-8161-962d4f1ea5cd.png)

CodeSandbox goes down quite often though, I suspect your issue might have been because of it being unable to fetch simple-keyboard-layouts.

![image](https://user-images.githubusercontent.com/25509135/126075577-83613253-b4bf-4b8a-842d-fb24493dd0fb.png)

Regards,
Francisco Hodge
