### ISSUE TITLE
VueJS incompatible

### ISSUE THREAD

**Issue by adoniskrasniqi** [hodgef/simple-keyboard#120]
Unable to use it on VueJS, because it does not work as a component.
Also please update ReadMe on Github, it's rather odd to read the docs on your personal page.

**Comment by hodgef** [comment]
Hello @adoniskrasniqi ,

If you're looking to use someone's software instead of creating your own, and would like to request help from the author, you should at least take the effort to explain the errors you've had and what you've tried.

I've seen this project used as a component in VueJS without issue.

Regarding the readme, thanks for the suggestion, but I'll decline.

Regards,
Francisco Hodge

**Comment by adoniskrasniqi** [comment]
**It does not work as a  component** meaning that you can not import, put it inside components object, then use it inside template as `<keyboard />`
Also if you have another item with class `simple-keyboard` inside the template, it crashes _simple keyboard_

**Comment by hodgef** [comment]
Check out this example of someone using simple-keyboard as a component in Vue:

https://github.com/MaksZhukov/vue-node-etranslate/blob/994ff56162d420341b56300073d6b7f33f341522/client/src/components/VirtualKeyboard.vue

Also, if you want to have multiple instances of `simple-keyboard`, you should give them a different class, otherwise they will override each other:

https://simple-keyboard.com/qa-use-cases/#give-different-class-keyboard

Regards

**Comment by just10minutes** [comment]
@adoniskrasniqi were you able to make it working using component option? I am also in need of such option. Provided example is slightly advanced for me to understand. Looking for a simple solution if there is any.

Thanks.

**Comment by hodgef** [comment]
Hello @just10minutes, @adoniskrasniqi,

I'm sorry for the trouble. I've updated the main VueJS demo to make it more component friendly:
[Check out the demo here](https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/?fontsize=14&module=%2Fsrc%2FApp.vue)

Regards,
Francisco Hodge

**Comment by just10minutes** [comment]
@hodgef Hat's off to you for making this demo. This will really help the needy like me who is not a pro on technologies.

Thanks once again
