### ISSUE TITLE
Moving the cursor via the drop shaped dot/object below the cursor in the middle of text and adding/removing character there is not working

### ISSUE THREAD

**Issue by gilroh** [hodgef/simple-keyboard#1441]
**Simple-keyboard version**
3.4.37

**Describe the bug**
Steps to reproduce:
1. Write text using the simple keyboard
2. Tap on the input field, so that the cursor and drop shaped object below it are visible at the end of the text
3. Drag the cursor via the tear shaped object somewhere in the middle of the of the text and try to add or remove character there

Expected result: Should be able to edit in the middle of the text

Actual result: the newly added or removed characters are at the end of the inputed text

This is happening only on devices where tapping in the input field shows the cursor and the drop shaped object below it like mobile devices and devices using electron. On PC it is not reproducible.

**Screenshots**
Video - https://drive.google.com/file/d/10BflpUrbEJi6XxH91vwtbtAoaLDVaRb5/view

**Comment by hodgef** [comment]
Hello @gilroh,

Check out this comment https://github.com/hodgef/simple-keyboard/issues/54#issuecomment-466733511. It links to a test sandbox that you can use to see if an event is fired when you drop the pin.

If no event is fired when you drop the pin, there's nothing I can do since I rely on `event.target.selectionStart`.

Regards,
Francisco Hodge
