### ISSUE TITLE
Error occurs on typing in a selected input field

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [hodgef/simple-keyboard#1522]
**Simple-keyboard version**
Using CDN     `script src="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.js"`

**Describe the bug**
If I type keys without selecting the field, everything works fine. However, once I select an input field - any typed keys are no longer entered into field. Instead an `(index):133 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector` error occurs. Please see shared screencast below.

**Screencast**
[https://www.awesomescreenshot.com/video/8652172?key=dbb0e9901cb9858ff44cc9deb6b9378c]()

**Comment by hodgef** [comment]
Hey @arnoldtonderaimarunda,

I don't think I have this selector anywhere in simple-keyboard's code. In my view this is likely an issue in your app's code. Can you share a sandbox or test git repository so I can run the code that's giving you this error?

Will reopen once I get that. Thanks!
Francisco Hodge

**Comment by arnoldtonderaimarunda** [comment]
Hi @hodgef 
Thanks for following up this issue. Below is link to sandbox with code.
https://codesandbox.io/s/simple-keyboard-issue-m9xtsr

**Comment by hodgef** [comment]
Thanks for the sandbox @arnoldtonderaimarunda. Your issue is in this part of the code:

```js
function onInputFocus(event) {
    selectedInput = `#${event.target.id}`;
    keyboard.setOptions({
        inputName: event.target.id
    });
}
```
As you can see `selectedInput` is set with the id of the selected input. But your input element does not have an id:
```html
<input class="input" name="code" placeholder="Card code" required="required" type="password">
```

You can debug these issues in the Chrome debugger. By clicking in the source link it takes you straight to the problematic line:

![image](https://user-images.githubusercontent.com/25509135/165927485-4028a359-d752-4e9d-9947-104144fed9c2.png)


Regards,
Francisco Hodge
