### ISSUE TITLE
react-simple-keyboard returns TypeError for handleMaxLength

### ISSUE THREAD

**Issue by teetlaja** [hodgef/simple-keyboard#1539]
**Simple-keyboard version**
"react-simple-keyboard": "^3.1.17",
"simple-keyboard": "^3.1.15"

**Describe the bug**

Got and TypeError from Sentry.
The keyboard input limit is defined as constant:
```javascript
export const TOUCH_KEYBOARD_INPUT_LIMITS = {
  orderNameInput: 25,
};
```

and the maxLength is defined as input attribute
```jsx
<Input
                bordered={false}
                maxLength={TOUCH_KEYBOARD_INPUT_LIMITS.orderNameInput}
                onChange={(e) => {
                  setOrderName(e);
                  profanityError && setProfanityError('');
                }}
                placeholder="Your Order Name"
                value={orderName}
                align="center"
                id="orderNameInput"
              />
```

The error appeared after clicking some button but not sure, which:
**ui.click** `div.hg-rows > div.hg-row`
`TypeError: Cannot read properties of undefined (reading 'length')`

Errors appeared to come from here>
[handleButtonClicked](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.ts#L490)
[handleMaxLength](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.ts#L426)

**Screenshots**

<img width="883" alt="image" src="https://user-images.githubusercontent.com/12461382/167414075-228901c8-92e5-41ad-8063-1777ab5942b1.png">

**Comment by hodgef** [comment]
Hey @teetlaja, sadly I'm a bit forced to close this since I have no repro and therefore cannot debug. Not sure what else to say since maxLength does work in a [sandbox](https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/uc-maxlength) and the types for it are very permissive. Let me know if you have a "debuggable" example of the issue and I will take a look.

Regards,
Francisco Hodge
