### ISSUE TITLE
virtual keyboard doesnt type

### ISSUE THREAD

**Issue by diomed** [hodgef/simple-keyboard#156]
**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
on official example, if I click letters via mouse, it types them.
but if I click on them via my keyboard, it doesn't type them.

**Comment by hodgef** [comment]
Hello @diomed,

When you type on your physical keyboard, simple-keyboard won't type. That is expected behavior, as  simple-keyboard only responds to _pointer events_.

 If you want simple-keyboard to respond to _key events_, you can code this as custom functionality. For example: Here's an approach I provided for issue #90 

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-4s4uv

Regards,
Francisco Hodge
