### ISSUE TITLE
physicalKeyboardHighlight issue with background: linear-gradient()

### ISSUE THREAD

**Issue by YungMilky** [hodgef/simple-keyboard#1641]
**Simple-keyboard version**
react-simple-keyboard 3.4.176 (tested on versions from a few of the sandboxes in the docs, including js version)

**Describe the bug**
Styling .hg-button on custom or default theme with background: linear-gradient(...) results in physicalKeyboardHighlight not displaying properly.

In [this sandbox repro](https://codesandbox.io/s/radial-gradient-background-highlight-forked-8gcdn9) forked from one of the sandboxes in the docs, you can only see highlight css from keys that don't have linear-gradient().

**Comment by hodgef** [comment]
Hey @YungMilky,

This is now fixed in the latest version of simple-keyboard and react-simple-keyboard.

You can use `physicalKeyboardHighlightBgColor` to pass in your `background` property value:
https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlightbgcolor/

The value passed there is applied to the button's style tag, as shown here:
https://github.com/hodgef/simple-keyboard/blob/ffb4bb3367a8036fb3b03b22175e75665f0fe565/src/lib/services/PhysicalKeyboard.ts#L50

Regards,
Francisco Hodge
