### ISSUE TITLE
Alternate Layouts with simplekeyboard_layout_mapping

### ISSUE THREAD

**Issue by tehChromic** [hodgef/simple-keyboard#172]
Hi Francisco,

I am building a library of modified language layouts to work with the layout mapping module you built - we need different character layout and shift keys defined.

Current issue: when I use the shift key to load the alternate layout, using your example here:
```
KeyboardControl.setOptions({
        layoutName: shiftToggle
      });

```
Shift itself works great but the layout mapping does not work for the shift keys unless I toLowerCase both the button key and the layout key in the mapping module. 

This must be because the mapping module is matching the key character to the layout character. Since my default source language is english this works well for the letter keys, but the number keys not so much once they have shifted.

I suppose the best answer is to create modified source layouts so that the shift keyboard is exactly the same as the default. Is this what you recommend? And if so I do not see an example for modifying source layout, any help is appreciated!

Thanks!

**Comment by hodgef** [comment]
Hello @tehChromic,

Before delving into the issue, I'd like to point out that as of `2.24.0`, `keyboard.physicalKeyboardInterface` has been renamed to `keyboard.physicalKeyboard`. If you update simple-keyboard, feel free to rename that property in your example as it's done here:

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-4s4uv

**Regarding the passing of a custom object as layout**

Since this is a custom implementation to accommodate #90, you should consider editing the sandbox to add the functionality you require. It would be a bit too much for me to continuously code custom implementations for developers (and variations thereof). My approach is to give you an initial example, that you can then take and edit to fit your requirements.

I'll break that rule (just this once !), cause I don't want to come empty handed:
https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-g3wwk

Feel free to inspect the edited code in that demo (namely in LayoutMapping.js line 16, and index.js line 13), and make further changes as needed.

Regards,
Francisco Hodge

**Comment by tehChromic** [comment]
Francisco,

Totally understand - you can't spend all your time on basic code that a
developer can pickup from any tutorial. In this case I did not understand
that a sourceLayout option could be a string or an object, and I probably
could have gathered that from the docs or the source code - pardon me.

However I am not sure I communicated the issue well. To be clear, the
layout mapping module will not work with shift mode given the example you
created unless the default and shift are the same for the sourceLanguage. I
assume this is because the physical key is mapped to the value of the
sourceLayout rather than a numeric index or key code.

At any rate, doing this here solves it for now:

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-odb56

I suppose if the keyboard is another language then the sourceLayout will
have to match their physical keyboard which makes some sense. I do wonder
if it might be more practical to map key index number to simple keys
instead as maybe that's a simpler solution, but not sure if this makes
sense from simplekeyboard pov.

Thanks for your time,
Christian

**Comment by tehChromic** [comment]
Dear Francisco,
Many pardons, but I have been working to implement as you suggested however
I may have uncovered a further bug. From your demo, simply commenting out
the module and passing these layout values produces unexpected behavior:

sourceLayout: "english",
targetLayout: "arabic" //,
//modules: [LayoutMapping]

The result ought to be an arabic keyboard, but it is english. Here is the
pen:

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-7ok9w

I believe you can recreate by simply uncommenting the module and again an
arabic keyboard is configured as target.

Many Thanks,
Christian

**Comment by tehChromic** [comment]
Francisco,

One more piece of the puzzle, and thank you again for patience, but I do
think there's a bug in here somewhere:

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-9cf7d

   - An error appears when a "layout" and the module are loaded, but that
   the error disappears when a targetLayout:"arabic" is set.
   - When the module is commented out, and "targetLayout" is set in
   addition to "layout", that in that case "layout" is used rather than
   "targetLayout".
   - When "layout" is set to a modified layout, shift fails to work,
   however typing on physical keyboard seems to produce shift key input.

It seems like the "layout" and "targetLayout" are similar ideas and may be
conflicting rather than providing an overlapping API option. It seems odd
to me that the module would have any effect on the layout, but it is
definitely the case in my demo.

Hopefully you can recreate, and thanks again for time and patience!

Best,
Christian

**Comment by hodgef** [comment]
Hello @tehChromic,

I'll recap:

1. The use case you're trying to accomplish is not supported by `simple-keyboard`.
2. Since this use-case is not supported, what we've done here is to create custom code.
3. This custom code was provided as a workaround you could try. It was not meant to be an extensive, bug-free, or plug-and-play solution.

[Like I said on May 29th..](https://github.com/hodgef/simple-keyboard/issues/90#issuecomment-497129959)

>If you take this as a base, just know that it's a rough/incomplete idea and **you'd have to improve it to fit your needs.**

I can't stress that enough, as it needs to be clear that this is some custom code for your project, and that I can't spend much time working on custom code for your project.

**Now, regarding your latest posts. Let's take a step back :**

Simple-keyboard's `layout` property is not compatible with the use-case you want to achieve. What you tried to do, per #90 is:

- To hit a key on your physical keyboard (which might have a QWERTY layout).
- This should trigger a button press in simple-keyboard. Namely, the virtual button positioned at the same location as the key in your physical keyboard.
- Moreover, simple-keyboard's layout is set to the Arabic language.

This use-case is not supported by the `layout` property, nor the `physicalKeyboardHighlight` property. It can't be done with simple-keyboard by default.

What [this example](https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-g3wwk) does is, **instead** of using `layout` (which doesn't work since it doesn't support what you're trying to achieve), we've **extended** simple-keyboard to add two new properties:

`sourceLayout` and `targetLayout`

"sourceLayout" should closely match your physical keyboard's layout, while "targetLayout" is the layout displayed to the user.

The logic is as follows:

- Once you press a key in your physical keyboard, we pass the key event through `keyboard.physicalKeyboard.getSimpleKeyboardLayoutKey(event)`, which is an internal method that `physicalKeyboardHighlight` uses. This returns what simple-keyboard thinks it's an equivalent key within `sourceLayout`.
- Once we have the key coords (row and button index) in the sourceLayout, we go search the key in `targetLayout` at that those coords. We then press it.

That logic could be executed in many ways. So please feel free to either edit the examples given or explore other solutions or alternative virtual keyboard libraries.

Unfortunately, I've spent more time than I'd like on this topic, so I will draw a line here.
I encourage you to visit [StackOverflow](https://stackoverflow.com/) if you have any following questions on this.

Thanks.
Francisco Hodge
