### ISSUE TITLE
Replacing input field selection does not work properly for single characters

### ISSUE THREAD

**Issue by chris-aux** [hodgef/simple-keyboard#1868]
Hi Francisco,
when using the simple-keyboard, I found this strange behavior which seems to be a bug.

**Simple-keyboard version**
Discovered with version 3.4.122 but also reproducible with the latest version in your codesandbox (https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/?from-embed).

**Describe the bug**
When you select exactly one character of the input text and try to type the selected character on the simple keyboard, it does not replace the selection correctly:
- Case 1: Input text is exactly one single character
  If you select the character and try to type the selected character on the simple keyboard once, I would expect that the input field contains the typed character again. But in fact, the input field content gets deleted.
![replace selection2](https://user-images.githubusercontent.com/125671455/219700071-cbf14952-48f0-410b-b1f1-37079532a86a.gif)

- Case 2: Input text has text with more than one character
  If you select a single character of a word and try to type the same on the simple keyboard as often as you want, I would expect that the selected character gets first replaced with the same typed character and with every further press on the keyboard, further characters are added at the cursor position. But in fact, the input field's text does not change at all.
![replace selection1](https://user-images.githubusercontent.com/125671455/219699396-e14a91a0-c995-4f4a-a09c-c6c584b8d96b.gif)

**Comment by chris-aux** [comment]
Thanks for quickly having a look at these issues! I really appreciate that very much!
When testing it with your codesandbox whose URL tells that it uses the current master branch, I unfortunately still encounter issues. Use case 2 from above where a character inside a word is selected and replaced seems to work now fine.

But I found a new strange behavior which might have arised with your latest changes. When you select the complete content of the input field (single character or multiple characters) and try to replace them, it sometimes does not delete the selection and replace it with the typed character. Instead, it appends the typed character:


![replace selection3](https://user-images.githubusercontent.com/125671455/223063378-39c24f04-8b72-428f-9d5f-480f30f6acc8.gif)

![replace selection4](https://user-images.githubusercontent.com/125671455/223063438-4c4aef48-b0af-4929-8edf-e35bb932337e.gif)

Can you please have a look at these issues as well? With this behavior, I cannot fix the bugs which my customer reported to me.

**Comment by hodgef** [comment]
This is a tough issue which I suspect may be due to a browser bug. If you enable `debug: true` you will notice that the `select` event listener is still reporting the old caret position after the selection is resolved:

![test03](https://user-images.githubusercontent.com/25509135/223148934-913f6a3f-0efc-41e6-8f61-8f0d31b90e30.gif)

If I remove this listener, then we get the latest issue you mentioned, which is worse. This is why I have reinstated the `select` listener. If you've got some spare time to also debug this I'd definitely welcome it! But for now this will remain as-is until I find some better solutions.
__________

Another thing you can try is to always keep the focus on the input. For this, check out the demos for `preventMouseDownDefault`:
https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/

**Comment by hodgef** [comment]
OK, I have added another tentative fix for the Case #2. Feel free to update and give it a try. Thanks!
