### ISSUE TITLE
[bug]: for physicalKeyboardHighlightPress

### ISSUE THREAD

**Issue by jinjilynn** [hodgef/simple-keyboard#2087]
**Simple-keyboard version**
 the latest.

**Describe the bug**
in your demo:
https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-layouts-demos/tree/chinese

just add two properties:

```javascript
let keyboard = new Keyboard({
  onChange: input => onChange(input),
  onKeyPress: button => onKeyPress(button),
  physicalKeyboardHighlightPress: true,
  physicalKeyboardHighlight: true,
  ...layout
});
```

after doing this, and  hit the keyboard  button like 'a' only once, you will get two 'a' or more in your output.

**Screenshots**
i just hit the 'a' only one time on the keyboard, and not holding it.
![image](https://github.com/hodgef/simple-keyboard/assets/12596042/79abdbe1-7e71-4036-861b-660416d47725)

**Videoshot**

https://github.com/hodgef/simple-keyboard/assets/12596042/ac2eacab-a971-4d0d-bf74-cc8151adee64

**Comment by hodgef** [comment]
This happens because you are focusing the input. Obviously when you focus the input and hit a key, it will write in the input. In addition, the keyboard listener will trigger simple-keyboard and hit the key again.

So the solution is not to focus the input in this scenario. 

Thanks,
Francisco Hodge
