### ISSUE TITLE
Not Displaying in IE 11 - Even the demo page

### ISSUE THREAD

**Issue by itssampath** [hodgef/simple-keyboard#212]
**Simple-keyboard version**
We tried to use Simple keyboard in Angular 8. Working fine in FireFox.

**Describe the bug**
Not Displayed in IE 11. I could see script error. 
Root cause is - In index.js 
(l = b.classList).add.apply(l, _toConsumableArray(t.getButtonThemeClasses(e)))
throws "Argument not optional"

**Screenshots**
Try opening demo page in IE 11. No Keyboard is displayed.

**Comment by hodgef** [comment]
Hello @itssampath,

simple-keyboard does not support Internet Explorer.

In a previous demo I had the following message shown:

![image](https://user-images.githubusercontent.com/25509135/63945243-f9d95b80-ca40-11e9-84ad-712263b23ba6.png)

I will look into adding it back just as a heads up to users.

Regards,
Francisco Hodge

**Comment by nicoabie** [comment]
I completely support the decision of the author @hodgef to not support IE11.
Unfortunately there exist cases where people are hired to make it work in IE11 because some institutions like banks still work with such browsers.

The issue here described is because IE11 does not support certain operations with multiple arguments in classList [see here](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)

In order to fix this a classList polyfill is required.

I suggest [this one](https://www.npmjs.com/package/eligrey-classlist-js-polyfill) which has the latest version of https://github.com/eligrey/classList.js. Be aware that most documentation will tell you to run `npm i --save classlist.js` but that one does **NOT** resolve this issue because it is outdated.

I leave this comment in case anyone has to make it work in IE11

**Comment by hodgef** [comment]
Thanks for sharing this fix @nicoabie ! Much appreciated

**Comment by hodgef** [comment]
Update: [simple-keyboard v3+](https://github.com/hodgef/simple-keyboard/releases/tag/3.0.0) now supports IE11 😄

Compatibility list: https://github.com/hodgef/simple-keyboard#compatibility-

>Please note : The demos (meant for devs) do not support IE, but the end product (the library) does.

Regards,
Francisco Hodge
