### ISSUE TITLE
Button Hold : Allow additional keys via options

### ISSUE THREAD

**Issue by bdorninger** [hodgef/simple-keyboard#2231]
**Is your feature request related to a problem? Please describe.**
We are using the keyboard with custom layouts, also adding some custom keys, which we would like to have handled on holding pressed.
Unfortunately, the keys, which can be handled here, are hardcoded. (But there is already a TODO, which sums up my request here.....)

**Describe the solution you'd like**
I wanna be able to handle HOLD for additional keys provided by options
Plus options should allow to alter the rate (currently fixed at 500ms)

**Describe alternatives you've considered**
None yet

**Additional context**
None

**Comment by hodgef** [comment]
Hello @bdorninger,

We've got a similar request here: #1544 

But I would suggest in the meantime to use the `layoutCandidates` option.
https://github.com/hodgef/simple-keyboard/issues/1544#issuecomment-1125562123

Thanks!
Francisco Hodge

**Comment by bdorninger** [comment]
OK, wasn't aware because I would have looked for OPEN issues ;-)

Have solved my required feature with the help of a module overwriting some methods. However, this might be fragile using future versions of simple-keyboard

**Comment by hodgef** [comment]
Sorry about the confusion - I normally close Proposals since I have the means to track them through the Enhancements project.

https://github.com/hodgef/simple-keyboard/projects/3#column-3744996

On my end there's no need to keep items open in that case. That being said everything is still searchable though Google or the Github search, and the status will be on the existing issue:

![image](https://github.com/hodgef/simple-keyboard/assets/25509135/7fbc7154-4da6-4112-80bb-d5509ad5fffe)

Glad you found an alternative approach to fit your needs! You can add unit tests on your end to make sure any future updates do not silently break it. But I would say that I do my best to keep the codebase stable.

Thanks,
Francisco Hodge

**Comment by bdorninger** [comment]
Thanks for clarifying this.
However, I'd have a PR solving this. 
According to your guidelines, I am asking before submitting it ;-)

**Comment by hodgef** [comment]
I appreciate that - but since it's an Enhancement, I would politely decline based on [item 1](https://github.com/hodgef/simple-keyboard/blob/master/CONTRIBUTING.md):

> 1. Use PRs to fix issues. New features are discouraged as they bring more maintenance burden over time.

I am trying to limit the maintenance overhead (via new features) from this library - since it's been taking up quite a bit of time since 2018. Though you are free to publish a module for it. It will definitely help people searching for this functionality.

**Comment by bdorninger** [comment]
OK, then I'll have to leave it. The module I made is merely a workaround until that enhancement is implemented. I would not consider it being a good solution, as it overrides handleButtonMouseDown and handleButtonHold. If these methods change in your repo, the module might then corrupt simple-keyboard
