### ISSUE TITLE
When multiple virtual keyboard instances are used, only one instance can get activeInputElement

### ISSUE THREAD

**Issue by dkc-1379** [hodgef/simple-keyboard#2301]
**Simple-keyboard version**: ^3.7.87
**Browser**: Chrome 126.0.6478.127
**OS**: Windows

**Describe the bug**

Run multiple keyboard demo: / SRC/demo/MultipleKeyboardsDestroyDemo. Js
When there are multiple virtual keyboard instances and you click the input element, you cannot get the correct **activeInputElement** in the onKeyPress callback because **this.dispatch()** used in the **caretEventHandler()** method does not properly update **activeInputElement** for each instance. Only the first instance can get **activeInputElement** in the onKeyPress callback.
If this is a bug, please allow me to fix it, if not, I want each virtual keyboard instance to provide an opportunity to get an **activeInputElement** when it updates the caret position. Thank you very much!

**Screenshots**
![image](https://github.com/hodgef/simple-keyboard/assets/173973581/0264f531-b1b7-4ffc-8b04-01666ad21ea5)
![image](https://github.com/hodgef/simple-keyboard/assets/173973581/583637f4-d1f2-4013-8b3f-a5e729360324)

**Comment by hodgef** [comment]
Hello @dkc-1379,

`this.activeInputElement` is an internal variable used to handle edge cases. I commented so in the codebase.
<img width="500" alt="image" src="https://github.com/hodgef/simple-keyboard/assets/25509135/4bbe7795-eb4c-4d9b-9d4e-df86e30c7c8b">

As such, it's not meant to be used externally. However, if you require all instances to receive the updated activeInputElement, you would need to edit the `caretEventHandler` method:

![image](https://github.com/hodgef/simple-keyboard/assets/25509135/cc89f76e-f672-4752-b774-91c4f0c1b516)

In there you can see a `this.activeInputElement = ...`. In addition you can add `instance.activeInputElement = ...`.

I would accept a PR from your part in order to have this change in. Feel free to submit it. Thanks!
