### ISSUE TITLE
Is there any working example for the integration of Japanese keyboard with IME input

### ISSUE THREAD

**Issue by simpleshobhit** [hodgef/simple-keyboard#2323]
**Is your feature request related to a problem? Please describe.**
We are trying to integrate Japanese layout to simple keyboard and need a way to integrate different combination of japanese language to integrate and have a n option to provide katakana, hiragana inputs and combine the letters to kanji characters, We are trying to us the Windows IME, but looking for any out of box solutions

**Describe the solution you'd like**
As the current Chineese keyboard layout provide option to select from upon entering the characters, something similar is it possible to do for japanese

**Describe alternatives you've considered**
We are considering using IME for combining and getting the values

**Additional context**

**Comment by hodgef** [comment]
Hello @simpleshobhit,

As you mentioned, there's the feature [layoutCandidates](https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/) which is an IME used in the [Korean](https://hodgef.com/simple-keyboard/demos/?d=korean) and [Chinese (Pinyin)](https://hodgef.com/simple-keyboard/demos/?d=chinese) layouts.

However for the Japanese layout, it still uses the old pre-layoutCandidates version. This is because I was not able to find any reference/code that I could use to generate a new layout for it. I need to either find existing code (and adapt it), or someone more familiar with the language could collaborate through a PR.

So sadly for now there's no out-of-box solution unless someone can share it with the community.

Regards,
Francisco Hodge

**Comment by simpleshobhit** [comment]
Thanks @hodgef 
Appreciate the response, if we are able to figure something out which can help the community would surely share.

**Comment by abkn9977** [comment]
Hi @hodgef ,

Thanks for building this awesome library.

When we switch windows to Japanese language, while typing using physical keyboard we get suggestions from Windows IME, from which we can select the candidate we want to use.

Is it possible to trigger Windows IME suggestion while using this keyboard ??

**Comment by hodgef** [comment]
Hello @abkn9977, I believe the message above (https://github.com/hodgef/simple-keyboard/issues/2323#issuecomment-2269800429) describes the current status correctly. Windows IME is different from simple-keyboard IME (layoutCandidates). In simple-keyboard, the Japanese layout does not have IME and we need a contribution from the community in order to support it.

Thanks,
Francisco Hodge
