### ISSUE TITLE
Change the behavior of `inputName` and allow keyboard to be inactive

### ISSUE THREAD

**Issue by niksajanjic** [hodgef/simple-keyboard#233]
**Is your feature request related to a problem? Please describe.**

I'm using one keyboard with all inputs in my app. I was a bit surprised when I realized that avoiding `inputName` creates `default` one for us.

For instance, let's say I have a keyboard shown constantly in my app at the bottom of the screen. In the beginning, `inputName` is `undefined` because I haven't focused any input. Once I focus an input, I set the `inputName` to the focused one. In case I focus some other input, I just update `inputName` again and so on. In case I click anywhere on the screen besides keyboard or any other input, I immediately set `inputName` back to undefined.

This flow allows me to prevent using the keyboard by mistake. Let's say I'm emulating mobile keyboard behavior, where my input is "focused" for as long as you're clicking on it or keyboard. Any other click on the screen would lose "focus" of that input (but wont hide the keyboard).

In the background, the keyboard is constantly active on every click, no matter if I have any input focused or not. In my state, I have 2 extra inputs saved, one is `default` which will get populated for as long as I don't focus my first input. Once I "blur" my input and set `inputName` back to `undefined` it will create `undefined` input and keep populating that one for the rest of the app when no other input is focused.

While I can just ignore this behavior (and not keep `default`/`undefined` inputs in my state), I'm worried about the fact that the keyboard is still keeping internal state for them. This is unnecessary and could potentially create memory issues for my app in the future. The thing is, my app will probably be on office touch screens that would run 24/7 which will keep populating unused input until it reaches excessively long string and keeps having memory leaks.

To prevent that, I can just clear that input every now and then, or even better, decide that I set `default` input every time I have no other inputs focused and keep it's maximum length to 0:
```js
maxLength={{
  default: 0
}}
```

While this solution will work, I don't think it should be accepted as a default solution, because it's up to devs to keep thinking about this issue and manually keep fixing it.

**Describe the solution you'd like**

I think `inputName` shouldn't be set to any default value. Furthermore, I think every time we pass `undefined` (and/or `null`) it should just make keyboard inactive for as long as you don't pass some value to it, similar as it makes it inactive when `maxLength` is reached. Another thing is, we should throw an error (or at least a warning) every time you pass any value as `inputName` besides string, `undefined` (and/or `null`). I understand that you can pass any string, even the one that doesn't exist, but that mistake is on dev, much more than we could blame him for `default`/`undefined`/`null`. Basically, we need a way to make keyboard inactive, even when we're using just one input.

**Describe alternatives you've considered**

I've explained my alternative solution in the first question :)

**Additional context**

I think this is a very low priority as there is a solution to the problem.

**Comment by hodgef** [comment]
Hello @niksajanjic,

Thank you for the detailed feedback and suggestions! I'll provide some insight into some of the aspects you've mentioned.

When building simple-keyboard, the main thought was to make it **independent from input elements**. This means you could have simple-keyboard output text wherever you wanted, be it a `div`, a `span`, you name it. You can see [this in action on the intro page](https://virtual-keyboard.js.org).

To achieve this, simple-keyboard tracks the input in the non-persistent `this.keyboard.input` object. The input is initialized under the key "default", unless you pass the `inputName` prop giving this key a name. [Here's the relevant part in the code.](https://github.com/hodgef/simple-keyboard/blame/4440b26a886f9bd52a63a3a5149e39ea987a1300/src/lib/components/Keyboard.js#L99).

The name "default" is just a name (for a lack of a better one) for the key where the current input will be saved. If inputName was `null` by default, we wouldn't be able to type on the keyboard. I wouldn't like to tell users that they have to pass `inputName` for their keyboard to work (please let me know if I misunderstood you on this part).

> **Does `keyboard.input` represent a memory leak?**

I personally don't think `keyboard.input` can lead to a memory leak in normal circumstances. This is because most kiosk apps clear the input/state on submit, when inactivity happens, etc. A simple call to [`keyboard.clearInput()`](https://github.com/hodgef/simple-keyboard/blob/4440b26a886f9bd52a63a3a5149e39ea987a1300/src/lib/components/Keyboard.js#L346) or [`keyboard.replaceInput({})`](https://github.com/hodgef/simple-keyboard/blob/4440b26a886f9bd52a63a3a5149e39ea987a1300/src/lib/components/Keyboard.js#L393) would get rid of any inputted data. 

> **Should passing `null` to `inputName` render the keyboard inactive?**

The main hesitation I have with this proposal is that is not a very intuitive way to disable the keyboard (in my opinion). I'd rather have an option e.g: `disable: true` that makes the keyboard unresponsive. However, you could also accomplish this by giving `.simple-keyboard` a style of `pointer-events: none` (and toggle it via css class), so this is why a `disable` option hasn't been put forward just yet.

> **Should simple-keyboard warn devs not to enter random data in the options?**

I think this would be desirable, just so devs are informed what's going to work or not.

Right now what we have is basically the docs with examples, and then it's up to the devs if they want to experiment. Heck, they can even [create their own module](https://franciscohodge.com/projects/simple-keyboard/modules/) and completely modify the keyboard's behavior if they want. So the approach is more of a permissive one for the sake of simplicity, but I see the value in being more strict with the input, just to avoid confusion (e.g: "why is this not working?!" moments)

Hope I was able to draw light into some of the choices made with this library. There's definitely room for improvement. My goal is to keep the codebase simple yet fast-track high impact features (those without any easy workarounds). I also have been rolling out [quite some breaking changes lately](https://github.com/hodgef/simple-keyboard/releases). So I'd like not to introduce breaking changes for the time being. That being said, I'll track this issue in the [Enhancement Proposals](https://github.com/hodgef/simple-keyboard/projects/3#column-3744996) to inspire future features and fixes.

Thanks again, and let me know if you have any questions or comments !

Regards,
Francisco Hodge

**Comment by niksajanjic** [comment]
Hi,

Thanks for your quick response. I like another approach you proposed with CSS (didn't think about it though). In my case, we decided to show/hide keyboard so it's no longer an issue for me to make the keyboard inactive while no input is focused. I still feel it might make sense to allow inactivity by some flag, but as we can see, there are multiple different ways to get around that with very little additional code so it's a very low priority.
