### ISSUE TITLE
Request for Multi-language Keyboard Support (e.g., Turkish, Arabic)

### ISSUE THREAD

**Issue by MehrdadArman** [hodgef/simple-keyboard#2333]
Thank you for maintaining and developing the Simple-keyboard package. It's a fantastic tool that offers great flexibility and customization for building virtual keyboards in web applications.

I would like to request a feature that would significantly enhance the usability of Simple-keyboard: multi-language keyboard support. Specifically, the ability to switch between different keyboard layouts, such as Turkish, Arabic, and other languages that have unique character sets.

Feature Request Details:

Multi-language Layouts: Add support for various international keyboard layouts, such as Turkish, Arabic, and others, to cater to a global audience.

Switching Mechanism: Implement a simple way to toggle between different language layouts within the same instance of the keyboard, either through a button on the keyboard itself or through an API method.

Custom Layout Definitions: Allow users to define custom layouts for languages not included by default, and easily switch between them.

This feature would greatly benefit developers who are building applications targeting users across different regions with different language requirements.

Thank you for considering this request! I believe that adding multi-language support will make Simple-keyboard an even more versatile and powerful tool.

**Comment by hodgef** [comment]
Hey @MehrdadArman,

Thanks for the suggestions. My goal with simple-keyboard is to deliver on essentials (which I believe are met) and leave the fine-tuning to the users (e.g.: developers paid to integrate simple-keyboard into apps). Before I adopted this stance I found out it takes too much of my time since the project inception in 2018.

For folks looking to get more involved: I provide hooks in the library to augment its functionality, through the [modules](https://hodgef.com/simple-keyboard/modules/) feature. Anyone is welcome to publish such integrations.

**So while I will not integrate the suggestion in the library core. I have put together a quick demo which should guide you in the right direction:**

https://codesandbox.io/p/sandbox/vigilant-lichterman-jv4972?file=%2Fsrc%2Findex.js

Thanks,
Francisco Hodge
