### ISSUE TITLE
When typing suddenly the 3rd or 4th letter goes in the front.

### ISSUE THREAD

**Issue by rizzaherrero** [hodgef/simple-keyboard#2393]
This is for selected desktop computer with touch screen feature.

When a user enter a word example: KING, while typing it the G goes in front (GKIN).

I cannot replicate the issue on my end. Is there a way we can prevent it from happening?

Thanks,
Rizza

**Comment by hodgef** [comment]
Hello @rizzaherrero, without debug information - there's not much I can do but flag as "Needs repro".

However I would like to share the following issue: https://github.com/hodgef/simple-keyboard/issues/54#issuecomment-466733511. In it theres a test sandbox (https://jsfiddle.net/fhodge/a3L69j2w/) that you can use to further debug this.

simple-keyboard itself is doing nothing magical under the hood. It's just listening to input events. If one of those events reports a wrong caret position, then the text will be input at the wrong spot. So by debugging with the sandbox above you can see if the issue also happens without simple-keyboard.

Another thing you can try is to prevent the loss of input focus. You can check out the demos in this page in order to accomplish this: https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/

Hope that helps,
Francisco Hodge
