### ISSUE TITLE
Keyboard dissapears with ngIf condition

### ISSUE THREAD

**Issue by nashfx** [hodgef/simple-keyboard#242]
I'm using the keyboard exactly as the angular example (https://franciscohodge.com/projects/simple-keyboard/demos/angular-basic-setup/)

If I place an If condition to show or hide the keyboard in the **simple-keyboard** div (or above div) the keyboard just disappears

```
<div style="text-align:center" *ngIf="show">
	<input (input)="onInputChange($event)" class="input" value={{value}} placeholder="Tap on the virtual keyboard to start" />
	<div class="simple-keyboard"></div>
</div>
<button (click)="show = !show">Show / Hide</button>
```

if you click the button the keyboard and the input should show/hide, but it remains disappeared

Do you have any clue why can this be happening?

**Comment by hodgef** [comment]
Hey @nashfx,

What's happening is basically simple-keyboard not finding the DOM element at initialization, which results in an error:

![image](https://user-images.githubusercontent.com/25509135/65657647-4b4e1980-dff2-11e9-9649-ef7dfec39740.png)

If you set show to "true" by default, it'll work. But then when you hide and show the keyboard again, it won't show anything, because simple-keyboard would have to be initialized again to populate the div.

This is why I generally do show-hide by toggling a css class. This way the element is still in the DOM and can be found by simple-keyboard. eg:

https://codesandbox.io/s/angular-simple-keyboard-704zq

Regards,
Francisco Hodge
