### ISSUE TITLE
jquery/js : old value in field is kept

### ISSUE THREAD

**Issue by werewolf7160** [hodgef/simple-keyboard#268]
I have create a fiddle based on the code sandbox : [https://jsfiddle.net/werewolf7160/afxobu9c/1/](url)
In simple, if enter some text(1), clear with the button(2) and re-enter some text(3), the previous text appear as it was not deleted.
1. (clicked on 'q' and 'w')
![image](https://user-images.githubusercontent.com/31860486/66379184-4192c180-e9b5-11e9-921b-183777a95483.png)

2.
![image](https://user-images.githubusercontent.com/31860486/66379234-5bcc9f80-e9b5-11e9-9f13-ac1d9133da7b.png)

3. (clicked on 'e')
![image](https://user-images.githubusercontent.com/31860486/66379296-730b8d00-e9b5-11e9-9f39-9e134d2a0e4e.png)

**Comment by werewolf7160** [comment]
I have resolve the problem by using `SimpleKeyboardInstances.simpleKeyboard.input.default='';` after I clean my input field.

**Comment by hodgef** [comment]
Glad you've solved it @werewolf7160!

You can also use [keyboard.clearInput()](https://simple-keyboard.com/documentation/#clearInput) to clear the internal input.

Regards,
Francisco Hodge

**Comment by DjoleDzele** [comment]
I'm having the exact same issue, tried everything i could think of to solve it but no luck, for example i have two separate input fields that are both registered and working with simple-keyboard, they accept inputs, but as shown in pictures above, after clearing inputs, and try typing again, it just resumes from the last string, i used ` keyboard.clearInput("#myInputId"); ` on each input, and cleared input fields with `form.reset()` , `input.value= ""`, `input.setAttribute("value", "");` , tried also `SimpleKeyboardInstances.simpleKeyboard.input.default='';` from the post above, but doesnt help, its still the same as those pictures, is there something else i could try. Also, when having multiple inputs, what actual parameter should i give to `keyboard.clearInput("#myInputId");` in order to clear all inputs? i tried with giving it the ID attribute name of inputs, since some other function of yours i saw seems to identify them and remember them by id?

**Comment by DjoleDzele** [comment]
UPDATE: It seems to work by using this combination of code:
`
document.querySelectorAll('.input').forEach(inp => {
  inp.focus();
  keyboard.clearInput();
  input.value = '';
})
`

**Comment by hodgef** [comment]
FYI, you can also pass an empty object to `keyboard.replaceInput` to clear the entire input object.
https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/
