### ISSUE TITLE
`simple-keyboard` CSS-Class is not set with custom selector

### ISSUE THREAD

**Issue by sense-it-gmbh** [hodgef/simple-keyboard#328]
**Simple-keyboard version** 2.27.27

**Describe the bug**

```html
<div 
  id="my-keyboard"
></div>
```

```javascript
new Keyboard("#my-keybord", {});
```

The keyboard is not styled properly since the `simple-keyboard` CSS-Class is missing on the root element.

*Expected behavior:* simple-keyboard is adding the CSS-Classes required for basic functionality (`simple-keyboard`)\
*Actual behavior:* the `simple-keyboard` class is missing 

EDIT: Adding the class in browser-devtools solves the problem, adding it in HTML-code has no effect since its getting removed during the setup.

**Screenshots**

![image](https://user-images.githubusercontent.com/42776598/70053147-1bfcef80-15d5-11ea-9547-ebfcb9df108e.png)

**Comment by hodgef** [comment]
Hello @sense-it-gmbh,

This is noted on the Q&A entry for "How to give a different base class to the keyboard":
https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/different-base-class/

The idea behind it was to allow people to opt-out entirely from the default styles by changing classes, instead of having to override them. However I think it'll be more intuitive to add an option for that, and have the default styles inherited by default.

That would be most likely a candidate for the next minor release (instead of an immediate bugfix), so I will close this ticket for now and track it on the Enhancements project.

Regards,
Francisco Hodge
