### ISSUE TITLE
Input Type Time

### ISSUE THREAD

**Issue by myvictorlife** [hodgef/simple-keyboard#334]
**Simple-keyboard version**
simple-keyboard@2.27.24

**Describe the bug**
I try to use the input type ''time" but it's not working.
I receive that message: 

The specified value "01:00 am" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

**Screenshots**
<img width="1293" alt="bug-input-type-time" src="https://user-images.githubusercontent.com/9218981/70268651-cffaa800-1798-11ea-9baf-3acb9e01203d.png">

**Comment by hodgef** [comment]
Hello @myvictorlife,

simple-keyboard works best with inputs of "text" type, more info on why can be found here: https://github.com/hodgef/react-simple-keyboard/issues/247#issuecomment-543791385

But the main reason it doesn't work with your use-case is that simple-keyboard is not aware that you're restricting your input element. When you tap on the buttons it'll track the input internally as entered (in `keyboard.input`), but then the browser will be expecting things in a specific format. So there's this disconnect going on.

So this is why I generally suggest only using inputs of text type.

Now, to accomplish what you're looking for, you can try a combination of the following:

- Input masking, through `simple-keyboard-input-mask`.
  - Demo: https://codesandbox.io/s/simple-keyboard-input-mask-demo-xxcmb
  - Docs: https://franciscohodge.com/projects/simple-keyboard/modules/input-mask/

- Input validation, like this:
  - https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-input-validation/

This doesn't fully match what you'd get through the "time" input type, but it's an alternative you can consider due to the support issues with the former.

Regards,
Francisco Hodge
