### ISSUE TITLE
Toggle layout button defined in layout

### ISSUE THREAD

**Issue by nbrignol** [hodgef/simple-keyboard#398]
Hi, thanks for this module !

Similar to your special `{command}` buttons, you could set a special layout toggle button that ... toggle the current layout defined in braces (or whatever).

Very handy because you can define layouts without implementing "handleShift"-like methods.

Exemple : 
```
layout: {
        
        'numeric': [
          '7 8 9',
          '4 5 6',
          '1 2 3',
          '{bksp} 0 (numericAlt)',
        ],

        'numericAlt': [
          '= / *',
          '- + ,',
          '{bksp} (numeric)',
        ]

}
```

**Comment by hodgef** [comment]
Hello @nbrignol! This is a nice proposal that would simplify the user code.

However, I think the current approach is more flexible, since it will be able to adapt to most use cases.

For example, If the user wants to do a check before changing a layout, or to call a function when a layout is changed, having a `handleShift` method would make this easier. If a layout changing key was added, there would also need to be a callback option for it, etc.

That being said, perhaps the code becomes too verbose to the point that your approach is needed. I'll track this ticket in the Enhancement proposals and implement it if it gets to that point.

Best,
Francisco Hodge

**Comment by nbrignol** [comment]
Yes of course you'll have to keep the current {command} approach ! 
Thank you again for this keyboard.
