### ISSUE TITLE
failure to load multiple keyboard instances in vuejs

### ISSUE THREAD

**Issue by Xenoha** [hodgef/simple-keyboard#402]
I forked your multiple input example to highlight something that I am experiences in a large application that has many components. It seems like the keyboard will only load with a single instance running on any one view. So, if I have multiple components that have different things going on in the view and want to have a keyboard for each one. It seems to not render the keyboards. Have you seen this before?

You can see this fork as a fast example to highlight. If you open the modal that has it's own simple keyboard component it does not render. Modals live web components are good examples where you might want to be able to load their own instance of a keyboard to allow for different teams to own their whole view and control for each input, etc.

Thoughts? Also, It is not easy to maintain code, and you do a fabulous job staying on top of issues and assisting others when their questions.

https://codesandbox.io/s/vue-simple-keyboard-7zj1e?fontsize=14&hidenavigation=1&theme=dark

**Comment by hodgef** [comment]
Hello @Xenoha!

The example you've listed shows how to handle multiple inputs with a single instance. To have **multiple instances** of simple-keyboard, you'll need to give a different class to each one. Otherwise, they'll just override each other.

[Here's some demos](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/multiple-keyboard-instances/). You can use the JS one as reference, although you'd need to adapt it to your needs. If you have any questions, feel free to let me know.

Regards,
Francisco Hodge

**Comment by Xenoha** [comment]
@hodgef thanks for the examples. I was able to get it working with the provided demos! Thanks again for the assistance!
