### ISSUE TITLE
Caps and Shift buttons trigger hide

### ISSUE THREAD

**Issue by erincarignan** [hodgef/simple-keyboard#47]
**Simple-keyboard version**
2.13.2

**Describe the bug**
I'm following the sample, [here](https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-showhide/), to show/hide the keyboard on input focus.

I notice that when the Caps or Shift buttons are clicked, the keyboard is hidden.  I'm guessing this is some behavior related to switching out the keyboard layout when those buttons are clicked, but I would expect that the keyboard would remain visible.

**Comment by hodgef** [comment]
Holy crap! Nice catch - I'll get this fixed asap. Please stand by for updates.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @erincarignan ,

The issue was that when `setOptions` was called simple-keyboard re-rendered, losing the "show-keyboard" class. I think the less complicated fix for now is to re-add this class after the `setOptions` call.

This whole process is certainly more lengthy than a simple "show/hide" option, but I think I shouldn't add show/hide logic to the core package as it implies listening to every click, and checking whether you clicked the input. As simple-keyboard doesn't rely on input elements, it might be more trouble than what it's worth.

You can find attached an updated sandbox here (note that both index.js and index.css have changed)

**Sandbox:** https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-showhide/

Feel free to react out if you have any further issues.

Francisco Hodge

**Comment by erincarignan** [comment]
Works great - thanks for the quick response!

**Comment by reksc** [comment]
I had exactly this issue today. A word about that calling `setOptions` might overwrite your custom class bindings should be in the docs :).
