### ISSUE TITLE
Adding empty rows to layout

### ISSUE THREAD

**Issue by omartoutounji** [hodgef/simple-keyboard#56]
**Is your feature request related to a problem? Please describe.**
I am trying to create a vertical square-like keyboard with simple-keyboard, it involves creating a lot of empty space between each letter. I want simple-keyboard to register those as empty, disabled buttons but it's registering each space as a button.

**Describe the solution you'd like**
I tried using display: { ' ':'' }. However it didn't work.

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Hello @omartoutounji,

Any character between spaces (even a space between spaces), is considered a button by design.

You could create an empty button like this `{//}` (built-in) or just create a custom empty button (like `{empty}`), then give it a desired style in CSS (though [buttonTheme](https://franciscohodge.com/projects/simple-keyboard/documentation/#buttonTheme)).

I'm not completely visualizing the use-case here though, a screenshot of what you're trying to achieve would really help. If padding between rows or buttons is needed, I generally would recommend using CSS.

Hope that helps. If it doesn't please provide a screenshot of what you're trying to achieve and we'll go from there.

Regards,
Francisco Hodge

**Comment by omartoutounji** [comment]
Hello @hodgef,

Thank you for your prompt reply. 

We are trying to create iType, a website allows you to type using your eye gaze which is tracked by your webcam. Fingers? Who needs them!

We tried 'eye-gazing' (as in typing by staring at a letter one-by-one for some time) on a QWERTY and it wasn't a pleasant experience as the letters are so close to each other. So to achieve a better user experience, we completely re-designed the QWERTY look to make it easier to type with your eyes.

We are now trying to implement that design using simple-keyboard, however empty spaces are replaced with empty buttons which we don't want.

Allow me to elaborate by attaching screenshots.

Below is the design we are trying to implement.
![keyboarddesign](https://user-images.githubusercontent.com/5984423/54047376-e55c8a80-41a4-11e9-8b20-b82c1c59213b.PNG)

Below is our implementation so far with simple-keyboard
![simplekeyboardimplementation](https://user-images.githubusercontent.com/5984423/54047466-1a68dd00-41a5-11e9-8f84-954ce3967734.PNG)

As you can see, those empty buttons look bad and the empty rows are clickable which we don't want!

**Comment by hodgef** [comment]
@omartoutounji Thanks for this info. I wonder though, couldn't you achieve this behavior through CSS?

Let's say you have this default layout:
```
[
  'c a z y x w v u',
  'd t',
  'e s'
  (etc..)
]
```
Then in CSS you'd target all the rows that are not the first nor the last one.
![image](https://user-images.githubusercontent.com/25509135/54048879-f7d8c300-41a8-11e9-8be2-14843301c9e1.png)

Perhaps like this
```
.simple-keyboard .hg-row:not(:first-child):not(:last-child) {
  justify-content: space-between;
}

.simple-keyboard .hg-row:not(:first-child):not(:last-child) .hg-button {
  flex-grow: unset;
  min-width: 50px;
}
```

Here's a sandbox:
https://codesandbox.io/s/2zx3my9qj0

Regards,
Francisco Hodge
