### ISSUE TITLE
 Long press implementation for keyboards with special characters

### ISSUE THREAD

**Issue by evertfreit77** [hodgef/simple-keyboard#58]
@hodgef 
Can this be done only with the features of that application? If yes, what would the implementation be like?
I need 'ç' or 'à' type characters when I click on a button, similar to what is done on Google Keyboard.
Tnks!

**Comment by hodgef** [comment]
Hello @evertfreit77,

This feature is not available out of the box unfortunately. It can be done custom however.

If you want to implement something like this, you could create a [simple-keyboard module](https://franciscohodge.com/projects/simple-keyboard/modules/) that would override the [`handleButtonHold`](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L277) method. You could also use this module to create and handle new simple-keyboard options (such as an option to store the special characters).

Here's an [example of a module](https://github.com/hodgef/simple-keyboard-autocorrect/blob/master/src/lib/components/Autocorrect.js#L22) (further details can also be found in the [modules page](https://franciscohodge.com/projects/simple-keyboard/modules/)).

I could support in case you do decide to go ahead and work on this feature - but unfortunately I don't think I'll have the time to implement it myself.

As such, I'll be closing this ticket, but I'll keep an eye on it in case you have questions.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
The new `layoutCandidates` option (available in v3) shows suggestions when you press a key. While not exactly the same as a long-press-triggered popup, it might provide equivalent functionality. Feel free to check it out:

https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/

![image](https://user-images.githubusercontent.com/25509135/111923089-ca9b9c80-8a73-11eb-9f1d-0d1fe103df05.png)

**Comment by cyclingcat** [comment]
Hi there,

@hodgef: First of all a big "thank you" from my side for this great piece of software which comes very handy for my Raspberry Pi touchscreen project! Up to now I was able to manage everything I needed for the keyboard input.

The functionality mentioned in the issue would be a further improvement though, and now that the `layoutCandidates` option is available I thought about combining this option with the `handleButtonHold` method via a new parameter which changes the buttonHold behaviour: Instead of repeating the same key the layoutCandidates box could appear if the key is held for a longer (configurable?) time. This way the layoutCandidate box would only appear if the user deliberately wanted to choose one of the additional keys by holding the key, which helps reduce confusion (and many users are used to this behaviour from their smartphones).

Would this be an idea for an enhancement that's not too complex to implement?

The cycling cat

**Comment by hodgef** [comment]
Hello @cyclingcat, I would appreciate if you could submit a PR for this! I'm open to this feature if it's behind an option and if the normal flow (with the feature off) remains unchanged.

Unless there's a contribution I'm not sure I will be able to pick it up anytime soon. Thanks for the understanding!
