### ISSUE TITLE
Downkeyboard logic in appleIOS keyboard

### ISSUE THREAD

**Issue by Centaurnia** [hodgef/simple-keyboard#582]
Hi, I'm using appleIOS keyboard in angular mode. It's very useful.
I need to hide the keyboard if I touch anywhere else in the page. Used on-focusout to hide the keyboard. 
onInputFocusOut() {
	this.keyboard.destroy();
}
But the keyboard gets hide even if I press the keyboard button.
My thought: I can see the downkeyboard button here. Can you please tell me the logic for the same?

I have referred this link. It contains js part. I need the same functionality in angular. 
<https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/uc-showhide>

<img width="622" alt="Firstshot" src="https://user-images.githubusercontent.com/64918196/84473529-dbc6aa00-aca6-11ea-9a4f-35b1bd8f67ff.PNG">
<img width="349" alt="Secondshot" src="https://user-images.githubusercontent.com/64918196/84473695-20524580-aca7-11ea-8c36-0a274cb28720.PNG">

**Comment by hodgef** [comment]
Hello @Centaurnia,

You can't use a input focus-out because the keyboard is not part of the input and would be hidden when you use it.

In the show/hide demo you've linked you can see an event being added to the document, which is what you need.

```
/**
 * Keyboard show toggle
 */
document.addEventListener("click", event => {
  if (
    // Target is not keyboard element
    event.target !== keyboard.keyboardDOM &&
    // Target is not the input
    event.target !== inputDOM &&
    // Target is not a keyboard button
    !event.target.classList.contains("hg-button")
  ) {
    hideKeyboard();
  }
});
```

You can also try libraries to detect click outside: https://www.npmjs.com/package/ng-click-outside

Regards,
Francisco Hodge

**Comment by Centaurnia** [comment]
Okay. I'll try this. Thank you 👍
