### ISSUE TITLE
Input isnt validated in Angular forms

### ISSUE THREAD

**Issue by tjadea** [hodgef/simple-keyboard#62]
**Simple-keyboard version**
Running 2.20.3

I have noticed that when using Angular form validation that even though the input does show (visually), the form.controls value and Angular validation (like ng-invalid if a field is set to required) do not update.

If you type into an input with the virtual keyboard and inspect the element the ng-reflect-model doesnt update.

This can be replicated within the simple-keyboard Angular demo in codesandbox.io. Importing FormModule in app.module.ts and NgForm in your component and creating a basic template driven form.

Any idea on a workaround for this? Forcing the form.controls to get the value doesn't work because the value still appears to be empty.

Thanks.

**Comment by hodgef** [comment]
Hello @tjadea,

Generally for these kind of use-cases I ask people to provide a sandbox example showing the issue. Could you please edit the following demo as to show the problem, and provide the new link?

https://codesandbox.io/s/github/hodgef/angular-simple-keyboard/tree/master/?module=%2Fsrc%2Fapp%2Fapp.component.ts

I'll reopen the ticket once that's done.

Best,
Francisco Hodge

**Comment by AmanChhabra-A746623** [comment]
once I give fix value to "value" variable, backspace does not work and on clicking any key it starts new input. Ideally it should continue to add input after value which is given in input. 

e.g I assigned value="abcd";

why is it so?

**Comment by hodgef** [comment]
Hello @AmanChhabra-A746623,

You need to update the internal simple-keyboard input with your default value. To do that, check out `setInput`.

https://simple-keyboard.com/documentation/#setInput

Regards,
Francisco Hodge

**Comment by pawel-elmi** [comment]
Hello @hodgef,

It seems that I run into the same problem. However I didn't manage to make it working on codesandbox, because of some dependencies problem, have a look at the repo I prepared:
https://github.com/pawel-elmi/SimpleKeyboardForms

What I figured out is that the refresh of the reactive form depends on "input" event which simple-keyboard(later S-K) doesn't emit. This can be seen clearly when you type sth using S-K (i.e "qwerty") the _input value is updated_ but the _form value is not_, unless you type any button on the **physical** keyboard - then the whole input shows up magically. 

Maybe you can give me a hint, how to resolve this problem.

PL.

**Comment by hodgef** [comment]
Hello @pawel-elmi,

If your 3rd-party dependency requires an event to be sent, you can send it yourself using `dispatchEvent`.

In your test repo, add the following line in the simple-keyboard `onChange` callback:
```
(<HTMLInputElement>document.getElementById(this.inputName)).dispatchEvent(new KeyboardEvent('input'));
```

Please feel free to create a new thread if you run into issues.

Regards,
Francisco Hodge
