### ISSUE TITLE
Customization of keyboard buttons spacing and large space button

### ISSUE THREAD

**Issue by hupptechnologies** [hodgef/simple-keyboard#63]
**Is your feature request related to a problem? Please describe.**
No, i want customize the layout of keyboard [Angular].

**Describe the solution you'd like**
I want to achieve keyboard same attached image below.

**Describe alternatives you've considered**
I can change button style by myself but problem is i want larger width space button and other key buttons height and width should be same and also spacing need to be same as attached screenshot.

[Stackblitz demo](https://stackblitz.com/edit/angular-mubw8e)

**Additional context**

**Keyboard I want**

![Screen Shot 2019-04-16 at 6 37 42 PM](https://user-images.githubusercontent.com/30364569/56261725-c03f2e00-60f9-11e9-9314-bae14278d2c0.png)

**Keyboard looks right now**

![Screen Shot 2019-04-17 at 10 13 34 AM](https://user-images.githubusercontent.com/30364569/56261766-ea90eb80-60f9-11e9-8f53-075ec03c90f8.png)

**Comment by hodgef** [comment]
Hello @hupptechnologies,

A couple observations:

- If your theme is very different from the default, it might be easier to set your own theme instead of overriding the default one:
https://simple-keyboard.com/documentation/#theme

- If you would like a subset of buttons in your row to have a different styling, you can use button grouping:
https://simple-keyboard.com/qa-use-cases/#button-containers

Here's an example:

![image](https://user-images.githubusercontent.com/25509135/56291658-ab5f9c00-60f3-11e9-8046-01a17dd798d2.png)

**Demo:** https://stackblitz.com/edit/angular-xjk4ge?file=src/app/keyboard/keyboard.css

Regards,
Francisco Hodge

**Comment by hupptechnologies** [comment]
@hodgef  Thank you so much. 😊 🙏
