### ISSUE TITLE
Backspace does not delete selected text

### ISSUE THREAD

**Issue by tuomassa** [hodgef/simple-keyboard#637]
**Simple-keyboard version**
2.29.72

**Describe the bug**
Selecting text and pressing backspace does not delete selected text

**Comment by hodgef** [comment]
Hello @tuomassa,

Thanks for reporting this, I'll have a look at it soon.

**Comment by tuomassa** [comment]
Thanks a lot for taking a look at it!

Another related behavior that virtual keyboard users are used to, is when you select a word for example and press any letter, it replaces selected text with that letter, without having to press backspace first

**Comment by hodgef** [comment]
Thanks @tuomassa, I added the changes to commit https://github.com/hodgef/simple-keyboard/commit/1f335f6b6262780f7613f977ae25aa36ce0bc92d. However, this added some issues with the [modules](https://hodgef.com/simple-keyboard/modules/). I'll put this task on hold for now while I fix these. When everything is ready, I'll post here and release to npm. Thanks!

**Comment by Centaurnia** [comment]
Hi @hodgef Any update on this issue?

**Comment by hodgef** [comment]
Hey @Centaurnia, really sorry for the delay. There was one modules bug that was driving me nuts.

I've now released v2.30.0 to a [staging dist](https://docs.npmjs.com/adding-dist-tags-to-packages) that you can use right away:

`npm install simple-keyboard@2.30.0 --save`

So for now it's accessible if you specify the version when installing (as shown above). This is because I still have to update the docs and do some more modules checking. Once I get that done I'll publish to the "latest" tag and mark this as truly complete.

Thanks!

**Comment by Centaurnia** [comment]
No Problem. Thanks a lot for the fix 👍

**Comment by karthikaanoop** [comment]
We tried this fix for backspace but it is not working as expected. 
When we select and do backspace, it is not getting deleted and also getting copy pasted as shown below -

Step1: Selecting multiple characters & Pressing backspace -The backspace doesnt delete the selected text.
![image](https://user-images.githubusercontent.com/28105296/91268017-2b8b1c80-e792-11ea-9f49-6f43790db5f8.png)

Step2: We try to click random key after the text not getting deleted. This results in copy pasting of previously selected text
![image](https://user-images.githubusercontent.com/28105296/91268212-8a509600-e792-11ea-9e3d-9ec191977227.png)

The cursor also remain in the middle of both the text sequences resulting in displaying the newly typed characters to appear in the middle

**Comment by Centaurnia** [comment]
Hi @hodgef, We get the same issue which @karthikaanoop posted in the above comment. Can you please take a look and give some solution.

**Comment by hodgef** [comment]
Hey guys, I cannot seem to reproduce this in the following 2.30.0 sandbox (Windows 10, Chrome 84):
https://codesandbox.io/s/festive-solomon-jpwl5

Can you reproduce that issue in the above sandbox? If not there might be something weird going on. Maybe it only happens on some devices.

Note: There's at least one limitation with the input selection at the moment. For instance, when you select the text your mouseup has to be within the input bounds (since we don't update caret unless event.target = an input). It's kind of a drawback but the alternative would be to save the last input element in a var which I wouldn't like to do.

Best,
Francisco Hodge

**Comment by hodgef** [comment]
Hello guys - I've gone ahead and merged selection support to master. New users that install simple-keyboard will be getting this functionality. I'll keep an eye out for any issues that might arise with caret positioning.

Thanks!
Francisco Hodge

**Comment by PozziCode** [comment]
Hi @hodgef,
if while I select the text I leave the input it does not work correctly.
I noticed it in this [example](https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/simple-keyboard-preventmodefault-caret-pos/tree/master).
![bug](https://user-images.githubusercontent.com/39779328/103894514-55b0fb80-50ef-11eb-8334-49e78a3cae09.gif)

**Comment by hodgef** [comment]
Hello @PozziCode,

Please refer to this comment:
https://github.com/hodgef/react-simple-keyboard/issues/896#issuecomment-722760244

>simple-keyboard's caret position handler is called on mouseup and checks if the mouseup event target is an input (that's where it will get the caret position from). Since [you're outside of the input], the mouseup target will be something else and caret position never updates.

If you come across issues please feel free to create a new ticket. Thanks!

Regards,
Francisco Hodge
