### ISSUE TITLE
Double Tap Issue

### ISSUE THREAD

**Issue by karthikaanoop** [hodgef/simple-keyboard#656]
We are getting double tap while clicking on the keys slowly like in the center when the span of the key character is coming. 
It is only coming when we click the individual key at the real center only. 
No issue if we press the full button as whole.

Looks like this is because disablebuttonhold property not working inside the span element. i.e if we press only the letter (inside the span), disablebuttonhold not working, we can still type the element continuously.

This issue is reproducible only while testing in the real device. 
Not occurring while testing in browser.

![image](https://user-images.githubusercontent.com/28105296/91267749-9f78f500-e791-11ea-929c-9da4e3ba7baa.png)

**Comment by hodgef** [comment]
Hello @karthikaanoop,

Does this also happen when using one of the following options?

- [autoUseTouchEvents](https://hodgef.com/simple-keyboard/documentation/options/autousetouchevents/)
- [useMouseEvents](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/)

I think your issue might be caused by PointerEvents being too sensitive, so hopefully the other pointer types (click/touch) work better for you.

Regards,
Francisco Hodge
