### ISSUE TITLE
New standard for the Hebrew keyboard

### ISSUE THREAD

**Issue by donno2048** [hodgef/simple-keyboard#677]
In the demos site (https://hodgef.com/simple-keyboard/demos/) there is an Hebrew keyboard which is ordered according to the old standard

The new standard changes only 7 places (marked in the picture below) so it would be easy to move them...

![](https://sm.pcmag.com/pcmag_il/photo/default/new-keyboard-layout_gkxd.jpg)

**Comment by hodgef** [comment]
Hey @donno2048,

Thanks for raising this issue. Do you mind [editing the layout](https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/hebrew.js) and submitting a PR for this? Otherwise a text character map/reference would really help (to be able to copy the characters).

It appears most places are still using the layout we already have, e.g:

https://www.branah.com/hebrew
http://kbdlayout.info/kbdhebl3/6.2.8250.0
https://en.wikipedia.org/wiki/Hebrew_keyboard#Standard_Hebrew_keyboard

Regards,
Francisco Hodge

**Comment by donno2048** [comment]
I submitted a [PR](https://github.com/simple-keyboard/simple-keyboard-layouts/pull/657)
