### ISSUE TITLE
API for closing keyboard

### ISSUE THREAD

**Issue by Doc999tor** [hodgef/simple-keyboard#704]
Simple-keyboard is a perfect, very flexible package  
Among the other features it has `.destroy` method but there is no nice way to call it   
I'd like to use some setting: `{ destroyOnBlur: true }` which will autoclose if the user clicked outside `.simple-keyboard` html wrapper
Maybe `simple-keyboard` has some similar functionality already?  
It's a very basic use case - to close the on-screen keyboard if I click somewhere else on the screen

**Comment by hodgef** [comment]
Hello @Doc999tor,

This is not built in since it would require simple-keyboard to know what's the input element (I try to keep the library as generic as possible). However you can add it without much effort.

Here's a guide on how to add this functionality (check out the "JS demo"):
https://hodgef.com/simple-keyboard/questions-answers/implement-show-hide-toggling/

Thanks!
Francisco Hodge
