### ISSUE TITLE
clearInput method does not fire onChange event

### ISSUE THREAD

**Issue by dblachut-adb** [hodgef/simple-keyboard#734]
**Simple-keyboard version**
https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.min.js
https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/css/index.css
https://cdn.jsdelivr.net/npm/simple-keyboard-key-navigation@latest/build/index.min.js

**Describe the bug**
calling clearInput method does not fire onChange("") event.

**Comment by hodgef** [comment]
Hello @dblachut-adb, this is as intended. The `onChange` callback is only fired when you press a button.

Methods such as `clearInput`, `setInput` and `replaceInput`, do not trigger onChange because if you call them you can handle other side effects at that same spot in the code without the need for onChange.

I think this has worked pretty well so far - however, if I get several requests to change this I'll be glad to revisit. I just don't want to introduce any potential breaking changes unless it is needed.

Thanks!
Francisco Hodge

**Comment by dblachut-adb** [comment]
Okay, no problem, thanks for the answer!
