### ISSUE TITLE
Setting internal keyboard caret position in input field not working properly for left and right arrow keys functionality

### ISSUE THREAD

**Issue by kirty0110** [hodgef/simple-keyboard#760]
Hello @hodgef,

I was trying to implement the left and right arrow keys functionality, but somehow I am unable to set the caret position in the input field. Also after setting the cursor at different position, the OnChange event is giving unexpected values.

Please find this sandbox that reproduces the issue- https://codesandbox.io/s/broken-water-xjo4u?file=/src/app/app.component.ts

Thank You,
@kirty0110

**Comment by hodgef** [comment]
Hello @kirty0110,

If you log the `keyboard.caretPosition` you'll notice that it is set to `null` by default. simple-keyboard only sets the caretPosition when it gets it from `element.selectionStart`, which only happens when you click on an input.

So in your case you need to handle the case when caretPosition is null.

Here's an example:
https://codesandbox.io/s/brave-chaplygin-xewwi?file=/src/app/app.component.ts

Note: In JS, you can set an input element's caret position with [setSelectionRange](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange).

Note 2: As a heads up, you would need to ensure that your arrow functionality doesn't trigger when it shouldn't (for example, you should be able to go back if your caretPosition is zero, or forwards if you're at the end of the input).

Regards,
Francisco Hodge
