### ISSUE TITLE
How to add a custom button having functionality of backspace button

### ISSUE THREAD

**Issue by kirty0110** [hodgef/simple-keyboard#761]
Hey @hodgef,

I want to add del button instead of backspace button. The functionality should be same as backspace button but it should appear as "del". And also if I wish to add some more buttons having functionality like the "Next Field" button, how should I proceed, please suggest. I want them to be used as function keys instead of typing keys.

Thanks,
@Kirty0110

**Comment by hodgef** [comment]
Hello @kirty0110,

You can add a `{backspace}` or a `{bksp}` button and label it as "del" with the [`display`](https://hodgef.com/simple-keyboard/documentation/options/display/) option.
https://codesandbox.io/s/sparkling-framework-x7kdq?file=/src/index.css

Regarding the next field button, this is custom functionality that you would have to implement. You can add a `{next}` button (when you put curly braces around your button name it becomes a function button instead of a typing key). Then, you would handle this `{next}` button in your `onKeyPress`.

Here's a similar issue, maybe it can help: https://github.com/hodgef/simple-keyboard/issues/703

Regards,
Francisco Hodge
