### ISSUE TITLE
types

### ISSUE THREAD

**Issue by benkas** [hodgef/simple-keyboard#8]
[ts]
Could not find a declaration file for module 'simple-keyboard'. 'd:/.../node_modules/simple-keyboard/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/simple-keyboard` if it exists or add a new declaration (.d.ts) file containing `declare module 'simple-keyboard';`

**Comment by hodgef** [comment]
Hello @benkas,

Are you using Angular? I can't see reproduce this error on the demo here:
https://codesandbox.io/s/48qqy8mn84

[![Edit simple-keyboard demo - Angular](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/48qqy8mn84)

This error may happen on your end because you have `noImplicitAny` enabled in your config tsconfig.json. Could you check if you do and disable it?

More information: https://github.com/Microsoft/TypeScript/issues/15031#issuecomment-291957621

I think that should solve your issue. If it doesn't let me know and I'll reopen the ticket.

Regards

**Comment by hodgef** [comment]
Hello @benkas - Just wanted to let you know that this should now be fixed as of 2.11.6 as per PR #40 by @armno.

Regards
