### ISSUE TITLE
Numeric input layout in RTL

### ISSUE THREAD

**Issue by Danieliverant** [hodgef/simple-keyboard#803]
**Simple-keyboard version**
"simple-keyboard": "^2.32.36",
"simple-keyboard-layouts": "^1.15.43",

**Describe the bug**

1. Why no numeric layout in the layouts package?
2. I've used the layout as in this example:
https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/numeric-theme

but in RTL it looks like that:

![image](https://user-images.githubusercontent.com/1301334/98963481-5a529c80-2510-11eb-907b-bcf614aac58c.png)

LTR for comparison:

![image](https://user-images.githubusercontent.com/1301334/98963618-7eae7900-2510-11eb-8a96-5f32355c653e.png)

**Comment by hodgef** [comment]
Hey @Danieliverant, there are no numeric layouts in simple-keyboard-layouts just because it's mostly used for language layouts.

I'll look into the styling issue when using RTL. Thanks!

**Comment by Danieliverant** [comment]
Thank you @hodgef!
but can you add it to the library? I think most of the users need the numeric layout also - and I would like to use only the NPM version and get updates every time you update it.

**Comment by hodgef** [comment]
Hello @Danieliverant,

I wanted to apply an upstream fix for your CSS issue by leveraging the [rtl option](https://hodgef.com/simple-keyboard/documentation/options/rtl/). However that option handles input rtl, not button rtl.

In this case your best bet is to simply add this CSS in your code:

```css
.hg-theme-default .hg-row .hg-button:not(:last-child) {
  margin-left: 5px;
  margin-right: unset;
}
```

Regarding the request to add the numeric layout in simple-keyboard-layouts, sadly I wouldn't add it since I don't want to break anyone's implementation until I deliver a major version.

What I mean is that some people may use `new Layouts().get()` to get all layouts, which until now have all been language layouts. If someone uses that to generate, say a dropdown of languages, and I add in a numeric layout, it will be a pain for the developer to have to filter any non-language layouts after each release.

Another simple-keyboard-layouts limitation is that it doesn't output CSS. Language layouts require no extra CSS so it is fine, but numeric layouts and others do require extra CSS. 

So while right now I'm not ready to deliver a simple-keyboard-layouts version addressing all that, I might pick this up in a future major release.

Regards,
Francisco Hodge
