### ISSUE TITLE
Hiding keyboard on first click

### ISSUE THREAD

**Issue by Amstergo** [hodgef/simple-keyboard#815]
Hello!

I am using your plugin and I really like it!

But I have a little problem with the inputMask module
I have multiply inputs on the page, and I need to show and hide the keyboard on click
If I don't use inputMask everything works fine, but as soon as I enable it the behavior breaks
When you first click on the keyboard, it hides, this should not happen

sendbox with a problem https://codesandbox.io/s/muddy-sun-liksf?file=/index.html
I could not solve this problem, please help.

Thanks in advance!

P.S. Sorry for my bad english =)

**Comment by hodgef** [comment]
Hey @Amstergo,

First of all, I'm very sorry that you had this annoying issue. This is the same issue that I saw on #47, but sadly I didn't update the docs and demos accordingly.

The issue is that the "show-keyboard" class is being lost due to a keyboard re-render. The mask module for example calls `setOptions` [here](https://github.com/simple-keyboard/simple-keyboard-input-mask/blob/master/src/index.js#L208). setOptions does a re-render, which means it [resets the classes](https://github.com/hodgef/simple-keyboard/blob/eff48f2485ed467d8cf5ca75d42187f65b5cf29f/src/lib/components/Keyboard.js#L591), deletes the keyboard contents and renders the rows from scratch.

So instead of attaching a class to the DOM element, we would need to pass it through simple-keyboard. A way to do this is through the [theme option](https://hodgef.com/simple-keyboard/documentation/options/theme/).

**Here's a fixed sandbox:**
https://codesandbox.io/s/modern-cookies-ukpfi?file=/src/index.js

I'm going to update the show/hide demos and add a note that when `setOptions` is called, the keyboard is re-rendered.

Thank you,
Francisco Hodge
