### ISSUE TITLE
when rtl=true keyboard add invisible string before and after the input

### ISSUE THREAD

**Issue by Danieliverant** [hodgef/simple-keyboard#834]
**Simple-keyboard version**
2.32.51

**Describe the bug**
When adding "rtl: true" to the keyboard config, every value from the "onChange" method returns with empty (invisible!) strings on the sides.

i.e. pressing 1 and splitting to an array will give you ('', '1', '');
or `'key-pressed'.charAt(0)` will give you an empty invisible string.

**to reproduce:**

your numeric layout demo - https://codesandbox.io/s/simple-keyboard-npm-demos-forked-6n9f8?file=/src/index.js:685-716

add "`rtl: true`" in the config and "`console.log(input.split(''))`" in the on change.

**Screenshots**
(see the console log)
![image](https://user-images.githubusercontent.com/1301334/101371047-fb840700-38b2-11eb-8227-c916270ae009.png)

**Comment by hodgef** [comment]
Hello @Danieliverant, this is intended for the `rtl` option.

Please refer to this issue for context:
https://github.com/hodgef/simple-keyboard/issues/712#issuecomment-709776091

Per v2.31.0 release notes:
>- Added `rtl` option
When set to `true`, this option adds [unicode directional control characters](http://unicode.org/reports/tr9/#Directional_Formatting_Codes) `\u202B` and `\u202C` to `onChange()` and `getInput()` returns. This helps to address issues when using simple-keyboard with right-to-left layouts.

https://github.com/hodgef/simple-keyboard/releases/tag/2.31.0

Regards,
Francisco Hodge

**Comment by Danieliverant** [comment]
@hodgef 
If I enter 1, and then try to parse this string to a number I can't because the string is actually `\u202B1\u202C` and it resolves to "NaN". 

Maybe add this unicode directional control characters only around special characters?
and not for letters or numbers and not in the start and end of the input.

i.e. if I press "123&5" it will be "123\u202B&\u202C5"

**Comment by hodgef** [comment]
I see.. I wonder though, why do you need simple-keyboard's rtl option here? The only purpose of that option is to add those control characters.

The reason these are added is to explicitly tell the browser to handle the whole input as left to right, This is because when you mix ltr ("western") and arabic characters for example, the browser gets confused and the output is messed up sometimes.

In your case, since you will only have numeric values, you wouldn't need `rtl: true` just `direction: rtl` in your CSS should do.

Regards,
Francisco Hodge

**Comment by Danieliverant** [comment]
@hodgef 
got it, thanks
