### ISSUE TITLE
Re-enabling key navigation fails to restore the active key CSS

### ISSUE THREAD

**Issue by cactilly** [hodgef/simple-keyboard#835]
**Simple-keyboard version**
2.32.33

**Simple-keyboard-key-navigation version**
2.3.57

**Describe the bug**
Expected behavior:
When using the simple-keyboard-key-navigation module, setting enableKeyNavigation to false will remove the active key CSS. Setting it to true after that will restore the active key CSS on the same key.

Bug:
Setting it to false does indeed remove the active key CSS, but setting it to true does not restore the active key CSS on any key. The hg-keyMarker class does not appear on any key. Navigating to another key works regardless and will show the active key CSS on that key.

**Comment by hodgef** [comment]
Hello @cactilly,

When the options are changed, the keyboard is [re-rendered according to the new options](https://hodgef.com/simple-keyboard/documentation/methods/setoptions/). Since the active button class is just attached to the button element (e.g.: not set through an option), the keyboard won't re-add it on re-render.

This is just a side-effect of the current [`setOptions`](https://hodgef.com/simple-keyboard/documentation/methods/setoptions/) logic. I don't think this issue warrants a change in that aspect, but you can definitely keep track of the last button pressed (through `onKeyPress`) and restore the active class as needed.

```js
// In your keyboard options
onKeyPress: (button) => {
  // You can save "button" somewhere
}

// Then, you can access the latest DOM element for that button as needed
const lastButtonPressed = keyboard.getButtonElement(button);
lastButtonPressed.classList.add("my-class");
```

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Looks like I missed the part where you referenced `hg-keyMarker`. I thought you were talking about `hg-activeButton` (the onPress class) for some reason. Sorry about that.

I've pushed a fix for your issue which should land with `simple-keyboard-key-navigation@2.3.78` in a couple minutes. Feel free to check it out.

Thanks!
Francisco Hodge

**Comment by cactilly** [comment]
Thanks, the new version looks good! No worries about the confusion.
