### ISSUE TITLE
Form "textarea" and "input" fields validation error

### ISSUE THREAD

**Issue by mohit1828** [hodgef/simple-keyboard#863]
Simple keyboard input values does not get validated inside a form.
Step 1: Enter values using touch keyboard (values will get displayed inside element)
Step 2: Press submit/next button on form and the entered input gets cleared and validation error is displayed along.

Your response will be appreciated.

**Comment by hodgef** [comment]
Hello @mohit1828,

Simple-keyboard just provides a way to turn button presses into a string. It's up to the developer to integrate that input with their application.

That is to say that validation issues are not caused by simple-keyboard. I'd suggest to try setting the input element's value directly with Javascript (`input.value = ...`) and see if they pass. That's essentially what is done in the [`onChange` handler](https://github.com/hodgef/simple-keyboard/blob/6fd4040aeb95b57bc4bea34e3817e5133bac58e1/src/demo/BasicDemo.js#L32).

That being said, I can try and find the issue in your code. If you want me to do that please provide a test repository or a sandbox demo per the [issue template](https://github.com/hodgef/simple-keyboard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md):

>**Simple-keyboard version**
>As some bugs have been addressed in later versions, please ensure you are running the latest.
>
>**Describe the bug**
>A clear and concise description of what the bug is. **Providing a [sandbox example](https://codesandbox.io/s/vanilla) or code depicting the issue is important, as this will help us reproduce the issue.**
>
>**Screenshots**
>If applicable, add screenshots to help explain your problem.

Regards,
Francisco Hodge
