### ISSUE TITLE
Show capitalize letter but work with lowercase and uppercase?

### ISSUE THREAD

**Issue by sasafister** [hodgef/simple-keyboard#896]
**Is your feature request related to a problem? Please describe.**
I would love to show keyboard in all capital letter, because that's how keyboard exist in real world, but behind the scenes, I would love to work with lowercase and uppercase letters.

**Describe the solution you'd like**
Some kind of settings like
```showKeyboardCapital: true```

**Comment by hodgef** [comment]
Hello @sasafister,

You can probably leverage the `display` property for that purpose, like so:
https://codesandbox.io/s/new-sunset-lkniw?file=/src/index.js

It's less elegant but can provide more flexibility.

Regards,
Francisco Hodge

**Comment by psugihara** [comment]
I'd also find this useful. For reference, we're adding the keyboard in a context where we only want capital letter input. I'd like to just show capital letters (easy with the layout prop) but "alias" capital and non-capital as the same letter so that if you hit "a" or "A" the key lights up with the physicalKeyboardHighlight prop. Couldn't figure out how to make that work with the module system.

For reference, here's how we're using it (though I'm disabling `physicalKeyboardHighlight` because of the above inconsistency).
<img width="530" alt="Screen Shot 2022-05-28 at 7 18 18 PM" src="https://user-images.githubusercontent.com/282016/170849292-22f30e29-859e-4528-aea9-346c78e72b33.png">
