### ISSUE TITLE
No override on selected text 

### ISSUE THREAD

**Issue by KerenGordon** [hodgef/simple-keyboard#928]
**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
A clear and concise description of what the bug is. Providing a [sandbox example](https://codesandbox.io/s/vanilla) or code depicting the issue is important, as this will help us reproduce the issue.

**Screenshots**

**Comment by KerenGordon** [comment]
When selecting text in an input and type, text is being added instead of override selected text. 
Can be reproduced in demo (see attachments):
1. type some text using keyboard.
2. select element - $0.select()
3. type again using keyboard.

![image](https://user-images.githubusercontent.com/28985810/111145480-f52bb800-8590-11eb-8c06-f844c9f3456a.png)
![image](https://user-images.githubusercontent.com/28985810/111145546-0b397880-8591-11eb-9cf8-5110d8ce20ae.png)
![image](https://user-images.githubusercontent.com/28985810/111145601-1c828500-8591-11eb-8c21-95e19f977fc8.png)

**Comment by hodgef** [comment]
Hey @KerenGordon, this is now fixed in the [staging branch](https://github.com/hodgef/simple-keyboard/tree/staging).

The fix will be published in the next couple days as part of the [3.0.0 release](https://github.com/hodgef/simple-keyboard/issues/920). I'll leave this ticket open until then.

Thanks!
Francisco Hodge

**Comment by hodgef** [comment]
v3.0.0 has been released. Closing.

Regards,
Francisco Hodge
