### ISSUE TITLE
On key pressed theme is not applied when change button theme

### ISSUE THREAD

**Issue by erazmerita** [hodgef/simple-keyboard#999]
**Simple-keyboard version**: 3.0.48

**Describe the bug**
We have a numeric keyboard and would like to block enter button when is not input value yet or value was deleted.
When we add or remove the button theme then pressed button is not shown (css is not applied on it).

Scenario:
- Press buttons: 1 and 'backspace'

Observed: 'backspace' blink is not shown.
Expected: 'backspace' should show blink.
Note: On pressing button 'backspace' we add disabled class for 'enter' button.

Demo repository: https://github.com/erazmerita/keyboard-test.git

**Comment by hodgef** [comment]
@erazmerita what do you mean by "backspace blink is not shown"/"should show blink"?

What I'm observing is that the enter button is given a the class `hg-disabled`, but I'm not clear on the expected behavior.

Thanks,
Francisco Hodge

**Comment by erazmerita** [comment]
@hodgef 
when press 'backspace' is setted class 'hg-activeButton':
![image](https://user-images.githubusercontent.com/60657830/116291322-1c36f580-a79d-11eb-801d-0eab22224c78.png)
and on release button this class is removed:
![image](https://user-images.githubusercontent.com/60657830/116291418-3a045a80-a79d-11eb-9275-0ed3101908ae.png)
so on click is looks like a blink, which is not happened when is making an additional changes on button theme:
![image](https://user-images.githubusercontent.com/60657830/116291922-cdd62680-a79d-11eb-9c27-ad3996b63a99.png)

**Comment by hodgef** [comment]
Hey Eugeniu,

Thanks for the additional information. `addButtonTheme` and `removeButtonTheme` re-render the keyboard when you call them. This means that "temporary" classes such as `hg-activeButton` will be removed.

What you can do is to call these methods on the [`onKeyReleased`](https://hodgef.com/simple-keyboard/documentation/options/onkeyreleased/) callback instead of the `onChange`. You can also add a small timeout to allow for the active class so be visible for a short time following button release.

Here's a snippet of your test with modifications:
```
// Added to simple-keyboard
onKeyReleased: (button) => {
    if(button === "{backspace}" && !this._keyboard.getInput()){
        this.disableEnter();
    }
}

...

private disableEnter() {
    const enterButton = this._keyboard.getButtonElement('{enter}') as KeyboardElement;

    if (!enterButton.classList.contains('hg-disabled')) {
      setTimeout(() => {
        this._keyboard.addButtonTheme('{enter}', 'hg-disabled');
        this._keyboard.removeButtonTheme('{enter}', 'hg-enabled');
      }, 100);
    }
}
```

Regards,
Francisco Hodge
